my_app/main/models.py
from my_app import db
import datetime


class Track(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128), nullable=False)
    artist = db.Column(db.String(128), default="Sam Gellaitry")
    description = db.Column(db.String(256), default=None)
    created_at = db.Column(db.DateTime(), default=datetime.datetime.utcnow())
    thumbnail = db.Column(db.String(256), nullable=False)
    audio = db.Column(db.Text, nullable=False)
    last_daily_sam = db.Column(db.DateTime(), default=None)

    def __repr__(self):
        return f"<Track: {self.title}>"


# thumbnail = db.Column(db.LargeBinary, nullable=False)
# binary_audio = db.Column(db.LargeBinary, nullable=False)

my_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FileField, SubmitField
from wtforms.validators import DataRequired


class AddTrackForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    artist = StringField("Artist")
    quote = TextAreaField("Quote", validators=[DataRequired()])
    quote_author = StringField("Author", validators=[DataRequired()])
    thumbnail = FileField("Upload Thumbnail", validators=[DataRequired()])
    binary_audio = FileField("Upload Audio", validators=[DataRequired()])
    submit = SubmitField("Submit")


class TrackRequestForm(FlaskForm):
    title = StringField("Song Title", validators=[DataRequired()])
    desc = StringField("Comments (optional)")
    submit = SubmitField("Submit")

my_app/__init__.py
from flask import Flask
from .config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_migrate import Migrate

db = SQLAlchemy()
bootstrap = Bootstrap()
migrate = Migrate()


def create_app():

    app = Flask(__name__)
    app.config.from_object(Config)

    from . import main

    app.register_blueprint(main.bp)

    db.init_app(app)
    bootstrap.init_app(app)
    migrate.init_app(app)

    from my_app.main.models import Track

    @app.shell_context_processor
    def shell_context():
        return {
            "db": db,
            "Track": Track,
        }

    return app

my_app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__, url_prefix="/")

from . import routes

my_app/main/routes.py
from . import bp
from my_app import db
from flask import (
    render_template,
    redirect,
    url_for,
    jsonify,
    make_response,
)
from .models import Track
from .forms import AddTrackForm
import random
from datetime import datetime
import time
from my_app.config import Config
from concurrent import futures
from .services import (
    add_one_file,
)
import json
import requests


@bp.route("/")
def index():
    """Homepage for the app. Displays every track in the db. TODO: Paginate"""

    tracks = Track.query.all()
    return render_template("index.html", title="Home", tracks=tracks)


@bp.route("/shuffle")
def shuffle():
    """Randomizes order that the tracks are displayed on the homepage"""

    tracks = Track.query.all()
    random.shuffle(tracks)

    return render_template(
        "shuffle.html",
        title="Shuffle Tracks",
        tracks=tracks
    )


@bp.route("/play_track/<track_id>/")
def play_track(track_id):
    """
    Purpose:
    This function is invoked for every track displayed on the page.
    It is imbedded in the HTML audio tag's src property and should
    return the audio to make the audio tag playable.

    Info on the track.audio property:
    Soundcloud makes an AJAX call to the url in track.audio which
    returns a response containing the .mpeg audio url. The response
    expires after one call and is programmatically generated on
    every request so no two responses are the same.
    This makes it a pain to work with.

    Goal:
    Simulate the soundcloud AJAX call for every track on the page,
    parse the .mpeg URL from the response and return the audio
    in a format that an HTML <audio> player can understand.
    """

    track = Track.query.filter_by(id=track_id).first()

    res = requests.get(track.audio)
    if not res.status_code == 200:
        return f"Initial request status code: {res.status_code}"

    json_res = json.loads(res.text)
    mpeg_audio_url = json_res["url"]

    msg_dict = {"url": mpeg_audio_url}

    res = make_response(jsonify({"message": msg_dict}))
    return res


@bp.route("/track_of_the_day")
def track_of_the_day():
    """
    Returns one track based on the day of the year, labeled "Track of the day"
    """

    day_of_year = datetime.now().timetuple().tm_yday
    daily_track_id = day_of_year % 365

    track = Track.query.filter_by(id=daily_track_id).first()

    if track.last_daily_sam != day_of_year:
        track.last_daily_sam = datetime.now().strftime("%b %m, %Y")

    return render_template(
        "daily_sam.html",
        title="Track of the day",
        track=track
    )


@bp.route("/add_local_tracks")
def add_local_tracks():
    """
    Original way of adding tracks to database. Adds tracks asynchronously.
    Requires mp3 and .jpg files already on local machine.

    Do not use: Should use add_json_tracks instead.
    """

    t0 = time.time()

    mp3_list = [x for x in Config.TRACKLIST_DIR if x.endswith(".mp3")]

    with futures.ThreadPoolExecutor(Config.MAX_WORKERS) as executor:
        res = executor.map(add_one_file, mp3_list)

    db.session.bulk_save_objects(list(res))
    db.session.commit()
    elapsed = time.time() - t0

    return f"Uploaded all tracks in {elapsed} seconds."


@bp.route("/add_track")
def add_track():
    """
    Endpoint to add a single track to the db.
    """

    form = AddTrackForm()
    if form.validate_on_submit():

        binary_audio = form.binary_audio.data
        thumbnail = form.thumbnail.data

        track = Track(
            title=form.title.data,
            description=form.description.data,
            thumbnail=thumbnail.read(),
            binary_audio=binary_audio.read(),
        )

        db.session.add(track)
        db.session.commit()
        print("Saved" + binary_audio.filename + "to the database.")
        return redirect(url_for("index"))

    return render_template("add_track.html", title="Add Track", form=form)

scraper/soundcloud/spiders/__init__.py
# This package will contain the spiders of your Scrapy project
#
# Please refer to the documentation for information on how to create and manage
# your spiders.

my_app/templates/_post.html
<div class="card mb-3">
    <div class="row no-gutters">
        <div class="col-xl-4 col-lg-5 col-md-4 col-sm-5">
            <img width="500px" height="500px" class="img-thumbnail thumb" src="{{ track.thumbnail }}" class="card-img" alt="{{ track.title }}">
        </div>
        <div class="col-xl-8 col-lg-7 col-md-6 col-sm-7">
            <div name="myCard" class="card-body myCard">
                {% if track.title|length > 20 %}
                <h5 class="card-title h5-title" title="{{track.title}}">{{ track.title|truncate(20, True) }}</h5>
                {% else %}
                <h5 class="card-title h5-title">{{ track.title }}</h5>
                {% endif %}
                <p class="card-text p-artist">{{ track.artist }}</p>
                <!-- <p class="card-text p-uploaded-at"><small class="text-muted">Uploaded on {{ track.created_at.strftime('%b %m, %Y') }}</small></p> -->
                <audio onplay="togglePlayButton(event);" onpause="togglePauseButton(event);" class="player" controls>
                    <source artist="{{track.artist}}" thumbnail="{{track.thumbnail}}" id={{track.id}} name="{{track.title}}" class="audio-player" src="{{ url_for('main.play_track', track_id=track.id) }}" type="audio/mpeg">
                    Your browser does not support the audio element.
                </audio>

            </div>
            
        </div>
    </div>




    <script>

        function replaceSource() {

            // A 3 day battle was waged on the backend trying to get the audio
            // player to refresh with the new src returned from the 
            // play_track/<track_id>/ response. This function took care of that.
            // Thank you Fetch API.

            let audio = document.getElementsByClassName('audio-player');
            let target = audio.item((audio.length)-1);
        
            fetch (`${target.src}`)
                .then((response) => {
                    return response.json();
                })
                .then((data) => {
                    target.src = data.message.url;
                    target.parentElement.load();
                })
        };

        document.addEventListener('load', replaceSource(event));



        function getCurrentTrack() {
            return nowPlaying[(nowPlaying.length)-1];
        }

        function appendCurrentTrack(event) {
            nowPlaying.push(event.target.childNodes[1]);
        }

        function removeCurrentTrack() {
            if (nowPlaying.length !== 0) {
                currentTrack = nowPlaying[0];
                nowPlaying.pop(currentTrack);   
            }  
        }

        function togglePauseButton(event) {
            
            let targetID = event.target.childNodes[1].getAttribute('id');
            let pauseButton = document.getElementById('pause');
            let pauseID = pauseButton.getAttribute('alt');
            if (targetID == pauseID) {
                removeCurrentTrack();
                let pauseButton = document.getElementById('pause');
                pauseButton.removeAttribute('class');
                pauseButton.setAttribute('class', 'fa fa-play')
            }
        }

        function togglePlayButton(event) {
            // Pause all other songs
            if (nowPlaying.length !== 0) {
                currentTrack = nowPlaying[0];
                currentTrack.parentElement.pause();
                nowPlaying.pop(currentTrack); 
            }

            // Add track to now playing array
            appendCurrentTrack(event);
            
            // Actually play the music
            
            event.target.play();

            // Overwrite footer with track info
            
            displayFooter(event);

            // Ensure footer pause button is in sync w/ audio player
            // let pauseButton = document.getElementById('pause');
            let pauseButton = document.getElementById('pause');
            pauseButton.removeAttribute('class');
            pauseButton.setAttribute('class', 'fa fa-pause')
            

        }

        function displayFooter(event) {

            // Get song info from clicked track
            let currentTrack = getCurrentTrack();
            currentTrackName = currentTrack.getAttribute('name');
            currentTrackID = currentTrack.getAttribute('id');
            currentTrackIMG = currentTrack.getAttribute('thumbnail');
            currentTrackArtist = currentTrack.getAttribute('artist');

            // Actually display the footer and relevant info
            let footer = document.getElementById('footer');
            if (footer.style.display == 'none') {
                footer.style.display = 'block';
                footer.style.borderBottom = 'none';
            }

            let currentThumbnail = document.getElementById('current-thumbnail');
            currentThumbnail.src = currentTrackIMG;

            let currentArtist = document.getElementById('current-artist');
            currentThumbnail.innerHTML = currentTrackIMG;
            
            let currentTitle = document.getElementById('current-title');
            currentTitle.innerHTML = currentTrackName;

            let playControls = document.getElementById('play-controls')
            playControls.childNodes[3].setAttribute('alt', currentTrackID);

        };

        function togglePauseControls(event) {
            let pauseID = event.target.getAttribute('alt');
            let source = document.getElementById(pauseID);
            let audio = source.parentElement;
            
            if (audio.paused) {
                audio.play();
            } else {
                audio.pause();
            }
        }

        function togglePrevButton() {
            let pauseID = document.getElementById('pause').getAttribute('alt');
            let prevID = (parseInt(pauseID) - 1);
            let prevTrack = document.getElementById(`${prevID}`);
            prevTrack.parentElement.play();
        }

        function toggleNextButton() {
            let pauseID = document.getElementById('pause').getAttribute('alt');
            let nextID = (parseInt(pauseID) + 1);
            let nextTrack = document.getElementById(`${nextID}`);
            nextTrack.parentElement.play();
        }

    </script>
</div>

my_app/templates/add_track.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>

{% endblock content %}

my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <title>Daily Sam Gellaitry</title>
        <link rel="stylesheet" href="../static/css/base.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand bg-none" href="{{ url_for('main.index') }}"><span class="span-title">Daily Sam Gellaitry</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active d-xl-none d-lg-none">
                        <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                    </li>
                    <li class="nav-item active d-xl-none d-lg-none">
                        <a class="nav-link" href="{{ url_for('main.shuffle') }}">Shuffle</a>
                    </li>
                    <li class="nav-item active d-xl-none d-lg-none">
                        <a class="nav-link" href="{{ url_for('main.track_of_the_day') }}">Track of the day</a>
                    </li>
                </ul>
            </div>
        </nav>
        <br><br>

        <div id="content-container" class="container">
            <div class="row">
                <div class="col-md-12 bg-black">
                    {% if not title %}
                        <h5>All tracks</h5>
                    {% else %}
                        <h5>{{ title }}</h5>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-xl-9 col-lg-8 col-md-12 col-sm-12 bg-black">
                    {% block content %}
                    {% endblock content %}
                </div>
                
                <div id="sidebar" class="col-xl-3 col-lg-4 col-md-0 col-sm-0 bg-black">
                    
                    <div id="sidebar-list" class="list-group">
                        <a href="{{ url_for('main.index') }}" class="list-group-item list-group-item-action">
                          Home
                        </a>
                        <a href="{{ url_for('main.track_of_the_day') }}" class="list-group-item list-group-item-action">Track of the day</a>
                        <a href="{{ url_for('main.shuffle') }}" class="list-group-item list-group-item-action">Shuffle</a>
                        <div id="night-mode" onclick="toggleNightMode(event)" class="list-group-item list-group-item-action">Night Mode</div>

                        <div onclick="toggleDisplay(event, 'toggle-projects')" class="list-group-item list-group-item-action">
                            My other projects
                            <ul class="list-group list-group-flush" id="toggle-projects" style="display: none;">
                                
                                <li onclick="event.stopPropagation()" class="list-group-item">
                                    <a href="http://48states4yang.com">48 States 4 Yang</a>
                                </li>
                                <li onclick="event.stopPropagation()" class="list-group-item">
                                    <a href="http://www.brianpioppo.com/notebook/">Digital Notebook</a>
                                </li>
                            </ul>
                            
                        </div>

                        <div onclick="toggleDisplay(event, 'toggle-follow')" class="list-group-item list-group-item-action">
                            Follow me
                            <ul class="list-group list-group-flush" id="toggle-follow" style="display: none;">
                                <li onclick="event.stopPropagation()" class="list-group-item">
                                    <a href="https://soundcloud.com/brianpioppo">Soundcloud</a>
                                </li>
                            </ul>


                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="footer" style="display: none;" class="footer container navbar fixed-bottom">

            <div class="row no-gutters">
                <div class="col-xl-1 col-md-1 col-sm-2 col-2">
                    <img id="current-thumbnail" src="" class="img-thumbnail" width="50px" height="50px">
                </div>
                <div class="col-xl-7 col-md-7 col-sm-7 col-7" style="padding: auto; margin-top: auto; margin-bottom: auto;">
                    <p id="current-title" style="margin: auto;" class="card-text"></p>
                    <p id="current-artist" style="margin: auto;" class="card-text">Sam Gellaitry</p>
                </div>
                <div id="play-controls" style="padding: auto; margin-top: auto; margin-bottom: auto;" class="col-xl-4 col-md-4 col-sm-3 col-3 text-right">
                    <p id="previous" onclick="togglePrevButton();" style="margin: auto;" class="fa fa-backward">&#160;</p>
                    <p id="pause" onclick="togglePauseControls(event);" style="margin: auto;" class="fa fa-pause">&#160;</p>
                    <p id="next" onclick="toggleNextButton();" style="margin: auto;" class="fa fa-forward"></p>
                </div>
            </div>
        </div>
        
    </body>


    <script>

        function toggleDisplay(event, id) {

            let ul = document.getElementById(id);

            if (ul.style.display == 'none') {
                ul.style.display = 'block';
            } else {
                ul.style.display = 'none';
            }

        };

        function toggleNightMode(event) {

            let nightMode = document.getElementById('night-mode');
            if (nightMode.innerHTML == 'Night Mode') {

                let body = document.getElementsByTagName('body')[0];
                body.style.backgroundColor = '#171717';

                let divs = document.getElementsByTagName('div'); 
                for (div of divs) {
                    div.style.backgroundColor = '#272727';
                }

                let bgBlacks = document.getElementsByClassName('bg-black');
                for (bgBlack of bgBlacks) {
                    bgBlack.style.backgroundColor = '#171717';
                    bgBlack.style.color = '#171717';
                }
                

                let ps = document.getElementsByTagName('p');
                for (p of ps) {
                    p.style.color = '#717171';
                }

                let hFives = document.getElementsByTagName('h5');
                for (hFive of hFives) {
                    hFive.style.color = '#717171';
                }

                let as = document.getElementsByTagName('a');
                for (a of as) {
                    a.style.backgroundColor = '#272727';
                }

                let bgNones = document.getElementsByClassName('bg-none');
                for (bgNone of bgNones) {
                    bgNone.style.color = '';
                    bgNone.style.backgroundColor = '';
                }

                let footer = document.getElementById('footer');
                footer.style.border = '0.5px solid #717171';

            } else {
                location.reload();
            }


            

        }

        let nowPlaying = []



    </script>

</html>

my_app/templates/daily_sam.html
{% extends 'base.html' %}

{% block content %}
    {% include '_post.html' %}

{% endblock content %}

my_app/templates/index.html
{% extends 'base.html' %}

{% block content %}

    {% for track in tracks %}
        {% include '_post.html' %}
    {% endfor %}

{% endblock content %}

my_app/templates/shuffle.html
{% extends 'base.html' %}

{% block content %}

    {% for track in tracks %}
        {% include '_post.html' %}
    {% endfor %}

{% endblock content %}